version: "3.8"
services:
  postgres:
    container_name: postgres
    image: "postgres:15.2"
    restart: unless-stopped
    env_file:
      - database.env
    expose:
      - "5437"
    command:
      - "-p 5437"
    ports:
      - "5437:5437"
    networks:
      - postgres
    volumes:
      - /var/docker-volumes/pg-ms-learn:/var/lib/postgresql/data/

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.12.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: veselovnikolay/eureka-server:1.0-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
    networks:
      - spring
      - postgres

  gateway:
    image: veselovnikolay/gateway:1.0-SNAPSHOT
    container_name: gateway
    ports:
      - "8083:8083"
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server

  customer-service:
    image: veselovnikolay/customer-service:1.0-SNAPSHOT
    container_name: customer-service
    ports:
      - "7071:7071"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - gateway
      - postgres
      - rabbitmq

  fraud-service:
    image: veselovnikolay/fraud-service:1.0-SNAPSHOT
    container_name: fraud-service
    ports:
      - "7076:7076"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres

  notification-service:
    image: veselovnikolay/notification-service:1.0-SNAPSHOT
    container_name: notification-service
    ports:
      - "7075:7075"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge