server:
  port: 7071

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5437/CustomerDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
